# syntax=docker/dockerfile:1

FROM python:latest
LABEL author="LangJin"
LABEL email="fenyukuang@163.com"
WORKDIR /usr/local/app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt -i https://pypi.douban.com/simple/

EXPOSE 3456

CMD [ "gunicorn", "main:app" , "-c", "gunicornConfig.py"]
